// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzjieiyvllmotgkjytov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6amllaXl2bGxtb3Rna2p5dG92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NzIyNTIsImV4cCI6MjA2ODI0ODI1Mn0.CE1WhsL-1sEBvLuczUjCPk4qqH59uAMFP-eNKnCpdlM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});